on:
  workflow_call:
    inputs:
      universe:
        description: Universe to take dependencies from
        type: string
      repository:
        description: URL to git repository containing R package
        type: string
        default: https://github.com/${{ github.repository }}
      ref:
        description: Commit-id or refname to build
        type: string
        default: ${{ github.sha }}
      subdir:
        description: Directory to find R package
        type: string
      binaries:
        description: Build and check on Windows and MacOS
        type: string
        default: 'true'
      organization:
        description: Run extra organization specific checks
        type: string
        default: ${{ github.repository_owner }}
      variables:
        description: Extra environment variables from R-universe
        type: string
        default: '{}'
    outputs:
      commitinfo:
        description: "Metadata from the commit"
        value: ${{ jobs.source.outputs.commitinfo }}
      maintainerinfo:
        description: "Metadata from the maintainer"
        value: ${{ jobs.source.outputs.maintainerinfo }}
      package:
        description: "Name of the package if build was tried"
        value: ${{ jobs.source.outputs.package }}
      version:
        description: "Version of the package"
        value: ${{ jobs.source.outputs.version }}
      biocchecks:
        description: "Check results from Bioconductor"
        value: ${{ jobs.bioconductor.outputs.checkresults }}

env:
  UNIVERSE_NAME: ${{ inputs.universe }}
  MY_UNIVERSE: ${{ inputs.universe && format('https://{0}.r-universe.dev', inputs.universe) || '' }}
  CRAN_VERSION: ${{ fromJSON(inputs.variables).CRAN_VERSION }}

jobs:
  source:
    name: Build source pkg and vignettes
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env: ${{fromJSON(inputs.variables)}}
    outputs:
      commitinfo: ${{ steps.build.outputs.COMMITINFO }}
      maintainerinfo: ${{ steps.build.outputs.MAINTAINERINFO }}
      sourcepkg: ${{ steps.build.outputs.SOURCEPKG }}
      package: ${{ steps.build.outputs.PACKAGE }}
      version: ${{ steps.build.outputs.VERSION }}
      java: ${{ steps.build.outputs.NEED_RJAVA }}
      jags: ${{ steps.build.outputs.NEED_JAGS }}
      cmdstan: ${{ steps.build.outputs.NEED_CMDSTAN }}
      fortran: ${{ steps.build.outputs.NEED_FORTRAN }}
      golang: ${{ steps.build.outputs.NEED_GOLANG }}
      cargo: ${{ steps.build.outputs.NEED_CARGO }}
      quarto: ${{ steps.build.outputs.NEED_QUARTO }}
      ostype: ${{ steps.build.outputs.OSTYPE }}
      compiled: ${{ steps.build.outputs.NEEDS_COMPILATION }}
      matrix_macos: ${{ steps.matrix.outputs.matrix_macos }}
      matrix_linux: ${{ steps.matrix.outputs.matrix_linux }}

    steps:
      - name: Free disk space on runner
        run: rm -Rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost" "$AGENT_TOOLSDIRECTORY" || true
      - id: build
        timeout-minutes: 60
        name: Build source package and vignettes
        uses: r-universe-org/build-source@master
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          url: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          subdir: ${{ inputs.subdir }}
          branch: ${{ fromJSON(inputs.variables).branch }}
          articles: ${{ fromJSON(inputs.variables).registered }}
      - name: "Store source package"
        uses: r-universe-org/actions/store-package@v11
        if: ${{ !cancelled() && steps.build.outputs.PACKAGE }}
        id: artifact
        with:
          name: package-source
          JOB_STATUS: ${{ job.status }}
          DISTRO: ${{ steps.build.outputs.DISTRO }}
          FILE: ${{ steps.build.outputs.SOURCEPKG }}
          TARGET: ${{ steps.build.outputs.SOURCEPKG && 'source' || 'failure' }}
      - name: "Store linux binary package"
        uses: r-universe-org/actions/store-package@v11
        if: ${{ !cancelled() && steps.build.outputs.BINARYPKG }}
        with:
          name: package-linux-release-x86_64
          JOB_STATUS: ${{ job.status }}
          DISTRO: ${{ steps.build.outputs.DISTRO }}
          FILE: ${{ steps.build.outputs.BINARYPKG }}
          TARGET: 'linux'
      - id: matrix
        if: always()
        run: |
          if [ "${{ steps.build.outputs.NEEDS_COMPILATION }}" ]; then
          echo 'matrix_macos=["x86_64","arm64"]' >> $GITHUB_OUTPUT
          echo 'matrix_linux=["x86_64","arm64"]' >> $GITHUB_OUTPUT
          else
          echo 'matrix_macos=["arm64"]' >> $GITHUB_OUTPUT
          echo 'matrix_linux=["x86_64"]' >> $GITHUB_OUTPUT
          fi
      - name: "${{'Conclude'}}: source: ${{ steps.build.outputs.RVERSION }}: ${{ steps.build.outcome == 'success' && 'OK' || 'ERROR' }}: ${{ steps.artifact.outputs.artifact-id }}"
        if: always()
        run: echo "Artifact URL ${{steps.artifact.outputs.artifact-url}}"

  linux:
    needs: [source]
    if: ${{ !cancelled() && needs.source.outputs.sourcepkg }}
    runs-on: ubuntu-24.04${{matrix.arch=='arm64' && '-arm' || ''}}
    timeout-minutes: 120
    name: Build R-${{ matrix.r }} for Linux ${{ needs.source.outputs.compiled && matrix.arch || '' }}
    strategy:
      fail-fast: false
      matrix:
        r: [ 'devel', 'release' ]
        arch: ${{fromJson(needs.source.outputs.matrix_linux)}}
    container:
      image: ghcr.io/r-universe-org/base-image:${{ matrix.r }}
    steps:
      - name: "Prepare Linux system"
        timeout-minutes: 10
        uses: r-universe-org/actions/linux-prep@v11
      - name: "Get dependences"
        id: deps
        uses: r-universe-org/actions/linux-deps@v11
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: Build package "${{needs.source.outputs.package}}"
        uses: r-universe-org/actions/linux-build@v11
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: "R CMD check"
        uses: r-universe-org/actions/linux-check@v11
        id: check
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: "Store binaries"
        id: artifact
        uses: r-universe-org/actions/store-package@v11
        if: ${{ always() && steps.check.outputs.binarypkg }}
        with:
          name: package-linux-${{ matrix.r }}-${{ matrix.arch }}
          overwrite: ${{ matrix.r == 'release' }}
          JOB_STATUS: ${{ job.status }}
          DISTRO: ${{ steps.check.outputs.distro }}
          FILE: ${{ steps.check.outputs.binarypkg }}
          CHECKSTATUS: ${{ steps.check.outputs.checkstatus }}
          TARGET: 'linux'
      - name: "${{'Conclude'}}: linux-${{ matrix.r }}-${{ matrix.arch }}: ${{ steps.deps.outputs.rversion }}: ${{ steps.check.outputs.checkstatus || 'FAIL' }}: ${{ steps.artifact.outputs.artifact-id }}"
        run: echo "Artifact URL ${{steps.artifact.outputs.artifact-url}}"
        if: always()

  windows:
    needs: [source]
    if: ${{ !cancelled() && needs.source.outputs.sourcepkg && inputs.binaries }}
    runs-on: 'windows-2025'
    timeout-minutes: 100
    name: Build R-${{ matrix.r }} for Windows
    strategy:
      fail-fast: false
      matrix:
        r: [ 'devel', 'release', 'oldrel' ]
    steps:
      - name: "Prepare Windows system"
        timeout-minutes: 10
        uses: r-universe-org/actions/windows-prep@v11
        with:
          java: ${{ needs.source.outputs.java }}
          jags: ${{ needs.source.outputs.jags }}
          quarto: ${{ needs.source.outputs.quarto }}
      - name: Install R-${{matrix.r}} for Windows
        timeout-minutes: 10
        uses: r-universe-org/actions/setup-r@v11
        id: install-r
        with:
          r-version: ${{ matrix.r }}
      - name: "Get dependences"
        id: deps
        uses: r-universe-org/actions/windows-deps@v11
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: Build package "${{needs.source.outputs.package}}"
        uses: r-universe-org/actions/windows-build@v11
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
          ostype: ${{ needs.source.outputs.ostype }}
      - name: "R CMD check"
        uses: r-universe-org/actions/windows-check@v11
        id: check
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: "Store binaries"
        id: artifact
        uses: r-universe-org/actions/store-package@v11
        if: ${{ always() && steps.check.outputs.binarypkg }}
        with:
          name: package-windows-${{ matrix.r }}
          JOB_STATUS: ${{ job.status }}
          DISTRO: windows
          FILE: ${{ steps.check.outputs.binarypkg }}
          CHECKSTATUS: ${{ steps.check.outputs.checkstatus }}
          TARGET: windows
      - name: "${{'Conclude'}}: windows-${{ matrix.r }}: ${{ steps.deps.outputs.rversion }}: ${{ steps.check.outputs.checkstatus || 'FAIL' }}: ${{ steps.artifact.outputs.artifact-id }}"
        run: echo "Artifact URL ${{steps.artifact.outputs.artifact-url}}"
        if: always()

  macos:
    needs: [source]
    if: ${{ !cancelled() && needs.source.outputs.sourcepkg && inputs.binaries }}
    runs-on: macos-${{ matrix.arch == 'x86_64' && '15-intel' || '15' }}
    timeout-minutes: 120
    name: Build R-${{ matrix.r }} for MacOS ${{ needs.source.outputs.compiled && matrix.arch || '' }}
    strategy:
      fail-fast: false
      matrix:
        r: [ 'devel', 'release' ]
        arch: ${{fromJson(needs.source.outputs.matrix_macos)}}
    steps:
      - name: "Prepare macOS system"
        timeout-minutes: 10
        uses: r-universe-org/actions/macos-prep@v11
        with:
          version: ${{ matrix.r }}
          fortran: ${{ needs.source.outputs.fortran }}
          golang: ${{ needs.source.outputs.golang }}
          jags: ${{ needs.source.outputs.jags }}
          quarto: ${{ needs.source.outputs.quarto }}
      - name: Install R-${{matrix.r}} for MacOS
        timeout-minutes: 10
        uses: r-universe-org/actions/setup-r@v11
        id: install-r
        with:
          r-version: ${{ matrix.r }}
      - name: "Get dependences"
        id: deps
        uses: r-universe-org/actions/macos-deps@v11
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: Build package "${{needs.source.outputs.package}}"
        uses: r-universe-org/actions/macos-build@v11
        timeout-minutes: 90
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: "R CMD check"
        uses: r-universe-org/actions/macos-check@v11
        id: check
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: "Store binaries"
        id: artifact
        uses: r-universe-org/actions/store-package@v11
        if: ${{ always() && steps.check.outputs.binarypkg }}
        with:
          name: package-macos-${{ matrix.r }}-${{ matrix.arch }}
          JOB_STATUS: ${{ job.status }}
          DISTRO: macos
          FILE: ${{ steps.check.outputs.binarypkg }}
          CHECKSTATUS: ${{ steps.check.outputs.checkstatus }}
          TARGET: macos
      - name: "${{'Conclude'}}: macos-${{ matrix.r }}-${{ matrix.arch }}: ${{ steps.deps.outputs.rversion }}: ${{ steps.check.outputs.checkstatus || 'FAIL' }}: ${{ steps.artifact.outputs.artifact-id }}"
        run: echo "Artifact URL ${{steps.artifact.outputs.artifact-url}}"
        if: always()

  wasm:
    needs: [source]
    if: ${{ !cancelled() && needs.source.outputs.sourcepkg }}
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    name: Build R-${{ matrix.r }} for Wasm
    strategy:
      fail-fast: false
      matrix:
        r: [ 'release' ]
    container:
      image: ghcr.io/r-universe-org/build-wasm${{ matrix.r == 'oldrel' && ':4.4' || '' }}
    steps:
      - name: "Prepare WebAssembly system"
        timeout-minutes: 10
        uses: r-universe-org/actions/linux-prep@v11
      - name: "Get dependences"
        id: deps
        uses: r-universe-org/actions/linux-deps@v11
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - id: build
        name: Build package "${{needs.source.outputs.package}}"
        uses: r-universe-org/actions/wasm-build@v11
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
          NEED_CARGO: ${{ needs.source.outputs.cargo }}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: "Store package files"
        id: artifact
        uses: r-universe-org/actions/store-package@v11
        if: ${{ always() && steps.build.outputs.binarypkg }}
        with:
          name: package-wasm-${{ matrix.r }}
          JOB_STATUS: ${{ job.status }}
          FILE: ${{ steps.build.outputs.binarypkg }}
          TARGET: "wasm"
      - name: "${{'Conclude'}}: wasm-${{ matrix.r }}: ${{ steps.deps.outputs.rversion }}: ${{ steps.build.outputs.binarypkg && 'OK' || 'FAIL' }}: ${{ steps.artifact.outputs.artifact-id }}"
        run: echo "Artifact URL ${{steps.artifact.outputs.artifact-url}}"
        if: always()

  bioconductor:
    needs: [source]
    if: ${{ !cancelled() && needs.source.outputs.sourcepkg && inputs.organization == 'bioconductor' }}
    runs-on: ubuntu-24.04
    timeout-minutes: 100
    name: Bioconductor Checks
    container:
      image: ghcr.io/r-universe-org/base-image:release
    outputs:
      checkresults: ${{ steps.check.outputs.checkresults }}
    steps:
      - name: "Prepare Linux system"
        timeout-minutes: 10
        uses: r-universe-org/actions/linux-prep@v11
      - name: "Get dependences"
        id: deps
        uses: r-universe-org/actions/linux-deps@v11
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: Run BiocCheck for "${{needs.source.outputs.package}}"
        uses: r-universe-org/actions/bioc-check@v11
        id: check
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: Store ${{needs.source.outputs.package}}.BiocCheck
        id: artifact
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: bioc-checks
          path: ${{needs.source.outputs.package}}.BiocCheck
      - name: "${{'Conclude'}}: bioc-checks: ${{ steps.deps.outputs.rversion }}: ${{ steps.check.outputs.checkstatus || 'FAIL' }}: ${{ steps.artifact.outputs.artifact-id }}"
        run: echo "Artifact URL ${{steps.artifact.outputs.artifact-url}}"
        if: always()

  ropensci:
    name: Build rOpenSci docs site
    runs-on: ubuntu-latest
    if: ${{ inputs.organization == 'ropensci' }}
    timeout-minutes: 90
    container:
      image: ghcr.io/ropensci-org/rotemplate:latest
    steps:
      - name: Build package docs
        timeout-minutes: 60
        id: build
        uses: ropensci-org/rotemplate@main
        with:
          repo_url: ${{ inputs.repository }}
          subdir: ${{ inputs.subdir }}
          r-version: 'skip'
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
      - name: "${{'Conclude'}}: pkgdown: ${{ steps.build.outputs.RVERSION }}: ${{ steps.build.outcome == 'success' && 'OK' || 'ERROR' }}: ${{ steps.build.outputs.artifact-id }}"
        run: echo "Artifact URL ${{steps.build.outputs.artifact-url}}"
        if: always()
