on:
  workflow_call:
    inputs:
      package:
        description: Which package or commit to build (default is HEAD commit)
        type: string
        required: false
      universe:
        description: Which universe to get dependencies from
        type: string
        required: false
    secrets:
      DUMMY_SESSION:
      CRANLIKEPWD:
      GH_APP_KEY:
      SLACK_TOKEN:
      BOT_TOKEN:

env:
  UNIVERSE_NAME:  ${{ inputs.universe || github.event.repository.name}}
  MY_UNIVERSE: ${{ format('https://{0}.r-universe.dev', inputs.universe || github.event.repository.name) }}
#  MY_UNIVERSE: ${{ github.event.repository.name != 'cran' && format('https://{0}.r-universe.dev', github.event.repository.name) || '' }}
  GH_APP_ID: '87942'

jobs:
  prepare:
    name: Determine package to build
    runs-on: ubuntu-24.04
    outputs:
      repo_url: ${{ steps.lookup.outputs.repo_url }}
      repo_name: ${{ steps.lookup.outputs.repo_name }}
      repo_commit: ${{ steps.lookup.outputs.repo_commit }}
      repo_subdir: ${{ steps.lookup.outputs.repo_subdir }}
      repo_branch: ${{ steps.lookup.outputs.repo_branch }}
      repo_registered: ${{ steps.lookup.outputs.repo_registered }}
      universe_app: ${{ steps.lookup.outputs.universe_app }}
      maintainer_login: ${{ steps.lookup.outputs.maintainer_login }}
      maintainer_uuid: ${{ steps.lookup.outputs.maintainer_uuid }}
      build_docs: ${{ steps.lookup.outputs.build_docs }}
      skip_binaries: ${{ steps.lookup.outputs.skip_binaries }}
      is_rebuild: ${{ steps.lookup.outputs.is_rebuild }}
      cran_version: ${{ steps.lookup.outputs.cran_version }}
      registry_metadata: ${{ steps.lookup.outputs.registry_metadata }}
      bioc_check: ${{ steps.lookup.outputs.bioc_check }}

    steps:
      - id: lookup
        name: Find changed package
        uses: r-universe-org/actions/find-changes@v10
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
#          github-token: ${{secrets.PUBLIC_PAT}}
          package: ${{ inputs.package }}
        env:
          CRANLIKEPWD: ${{ secrets.CRANLIKEPWD }}

  pendingstatus:
    name: Set Status to Pending
    runs-on: ubuntu-24.04
    needs: [prepare]
    if: needs.prepare.outputs.universe_app && !needs.prepare.outputs.is_rebuild
    steps:
      - name: Set upstream commit status
        uses: r-universe-org/commit-status@master
        env:
          GH_APP_KEY: ${{ secrets.GH_APP_KEY }}
        with:
          repo: ${{ needs.prepare.outputs.repo_url }}
          sha: ${{ needs.prepare.outputs.repo_commit }}
          url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          universe: ${{ github.event.repository.name }}
          has_app: ${{ needs.prepare.outputs.universe_app }}
          package: ${{ needs.prepare.outputs.repo_name }}
          deployed_packages: 'pending'

  docs:
    needs: prepare
    name: Build pkgdown site (ropensci only)
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    container:
      image: ghcr.io/ropensci-org/rotemplate:latest
    if: needs.prepare.outputs.build_docs
    steps:
      - name: Build package docs
        timeout-minutes: 60
        id: build
        uses: ropensci-org/rotemplate@main
        with:
          repo_url: ${{ needs.prepare.outputs.repo_url }}
          subdir: ${{ needs.prepare.outputs.repo_subdir }}
          r-version: 'skip'
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
      - name: "${{'Conclude'}}: pkgdown: ${{ steps.build.outputs.RVERSION }}: ${{ steps.build.outcome == 'success' && 'OK' || 'ERROR' }}"
        if: always()
        run: echo "print status to logs"

  deploydocs:
    name: Deploy to docs server
    runs-on: ubuntu-24.04
    needs: docs
    steps:
      - name: Get artifacts for deployment
        uses: actions/download-artifact@v7
        with:
          name: docs-website
          path: docs-website
      - id: deployment
        name: Upload docs to server
        uses: r-universe-org/deploy-docs@master
        env:
          BUILDLOG: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          GITHUB_PAT: ${{ secrets.BOT_TOKEN }}

  source:
    needs: prepare
    name: Build source pkg and vignettes
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    outputs:
      commitinfo: ${{ steps.build.outputs.COMMITINFO }}
      maintainerinfo: ${{ steps.build.outputs.MAINTAINERINFO }}
      sourcepkg: ${{ steps.build.outputs.SOURCEPKG }}
      package: ${{ steps.build.outputs.PACKAGE }}
      version: ${{ steps.build.outputs.VERSION }}
      java: ${{ steps.build.outputs.NEED_RJAVA }}
      jags: ${{ steps.build.outputs.NEED_JAGS }}
      cmdstan: ${{ steps.build.outputs.NEED_CMDSTAN }}
      fortran: ${{ steps.build.outputs.NEED_FORTRAN }}
      golang: ${{ steps.build.outputs.NEED_GOLANG }}
      cargo: ${{ steps.build.outputs.NEED_CARGO }}
      quarto: ${{ steps.build.outputs.NEED_QUARTO }}
      ostype: ${{ steps.build.outputs.OSTYPE }}
      compiled: ${{ steps.build.outputs.NEEDS_COMPILATION }}
      matrix_macos: ${{ steps.matrix.outputs.matrix_macos }}
      matrix_linux: ${{ steps.matrix.outputs.matrix_linux }}

    steps:
      - name: Free disk space on runner
        run: rm -Rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost" "$AGENT_TOOLSDIRECTORY" || true
      - id: build
        timeout-minutes: 60
        name: Build source package (including vignettes)
        uses: r-universe-org/build-source@master
        env:
          MAINTAINERLOGIN: ${{ needs.prepare.outputs.maintainer_login }}
          MAINTAINERUUID: ${{ needs.prepare.outputs.maintainer_uuid }}
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
          DUMMY_SESSION: ${{secrets.DUMMY_SESSION}}
          CRAN_VERSION: ${{ needs.prepare.outputs.cran_version }}
          REGISTRY_METADATA: ${{ needs.prepare.outputs.registry_metadata }}
        with:
          url: ${{ needs.prepare.outputs.repo_url }}
          ref: ${{ needs.prepare.outputs.repo_commit }}
          subdir: ${{ needs.prepare.outputs.repo_subdir }}
          branch: ${{ needs.prepare.outputs.repo_branch }}
          articles: ${{ needs.prepare.outputs.repo_registered }}
      - name: "Store source package"
        uses: r-universe-org/actions/store-package@v10
        if: ${{ always() && steps.build.outputs.PACKAGE }}
        id: artifact
        with:
          name: package-source
          JOB_STATUS: ${{ job.status }}
          DISTRO: ${{ steps.build.outputs.DISTRO }}
          FILE: ${{ steps.build.outputs.SOURCEPKG }}
          TARGET: ${{ steps.build.outputs.SOURCEPKG && 'source' || 'failure' }}
      - name: "Store linux binary package"
        uses: r-universe-org/actions/store-package@v10
        if: ${{ always() && steps.build.outputs.BINARYPKG }}
        with:
          name: package-linux-release-x86_64
          JOB_STATUS: ${{ job.status }}
          DISTRO: ${{ steps.build.outputs.DISTRO }}
          FILE: ${{ steps.build.outputs.BINARYPKG }}
          TARGET: 'linux'
      - name: "Cache package library"
        uses: actions/cache/save@v4
        if: ${{ always() && steps.build.outputs.BINARYPKG }}
        with:
          path: ${{ github.workspace }}/pkglib
          key: ${{ runner.os }}-${{ github.run_id }}-${{github.run_attempt}}
      - id: matrix
        if: always()
        run: |
          if [ "${{ steps.build.outputs.NEEDS_COMPILATION }}" ]; then
          echo 'matrix_macos=["x86_64","arm64"]' >> $GITHUB_OUTPUT
          echo 'matrix_linux=["x86_64","arm64"]' >> $GITHUB_OUTPUT
          else
          echo 'matrix_macos=["arm64"]' >> $GITHUB_OUTPUT
          echo 'matrix_linux=["x86_64"]' >> $GITHUB_OUTPUT
          fi
      - name: "${{'Conclude'}}: source: ${{ steps.build.outputs.RVERSION }}: ${{ steps.build.outcome == 'success' && 'OK' || 'ERROR' }}: ${{ steps.artifact.outputs.artifact-id }}"
        if: always()
        run: echo "Artifact URL ${{steps.artifact.outputs.artifact-url}}"

  linux:
    needs: [prepare, source]
    if: ${{ always() && needs.source.outputs.sourcepkg }}
    runs-on: ubuntu-24.04${{matrix.arch=='arm64' && '-arm' || ''}}
    timeout-minutes: 120
    name: Build R-${{ matrix.r }} for Linux ${{ needs.source.outputs.compiled && matrix.arch || '' }}
    strategy:
      fail-fast: false
      matrix:
        r: [ 'devel', 'release' ]
        arch: ${{fromJson(needs.source.outputs.matrix_linux)}}
    container:
      image: ghcr.io/r-universe-org/base-image:${{ matrix.r }}
    steps:
      - name: "Prepare Linux system"
        timeout-minutes: 10
        uses: r-universe-org/actions/linux-prep@v10
      - name: "Get dependences"
        id: deps
        uses: r-universe-org/actions/linux-deps@v10
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
          CRAN_VERSION: ${{ needs.prepare.outputs.cran_version }}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: Build package "${{needs.source.outputs.package}}"
        uses: r-universe-org/actions/linux-build@v10
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
          CRAN_VERSION: ${{ needs.prepare.outputs.cran_version }}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: "R CMD check"
        uses: r-universe-org/actions/linux-check@v10
        id: check
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: "Store binaries"
        id: artifact
        uses: r-universe-org/actions/store-package@v10
        if: ${{ always() && steps.check.outputs.binarypkg }}
        with:
          name: package-linux-${{ matrix.r }}-${{ matrix.arch }}
          overwrite: ${{ matrix.r == 'release' }}
          JOB_STATUS: ${{ job.status }}
          DISTRO: ${{ steps.check.outputs.distro }}
          FILE: ${{ steps.check.outputs.binarypkg }}
          CHECKSTATUS: ${{ steps.check.outputs.checkstatus }}
          TARGET: 'linux'
      - name: "${{'Conclude'}}: linux-${{ matrix.r }}-${{ matrix.arch }}: ${{ steps.deps.outputs.rversion }}: ${{ steps.check.outputs.checkstatus || 'FAIL' }}: ${{ steps.artifact.outputs.artifact-id }}"
        run: echo "Artifact URL ${{steps.artifact.outputs.artifact-url}}"
        if: always()

  wasm:
    needs: [prepare, source]
    if: ${{ always() && needs.source.outputs.sourcepkg }}
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    name: Build R-${{ matrix.r }} for WebAssembly
    strategy:
      fail-fast: false
      matrix:
        r: [ 'release' ]
    container:
      image: ghcr.io/r-universe-org/build-wasm${{ matrix.r == 'oldrel' && ':4.4' || '' }}
    steps:
      - name: "Restore package library"
        uses: actions/cache/restore@v4
        if: matrix.r == 'release'
        with:
          path: ${{ github.workspace }}/pkglib
          key: ${{ runner.os }}-${{ github.run_id }}-${{github.run_attempt}}
          restore-keys: ${{ runner.os }}-${{ github.run_id }}
          enableCrossOsArchive: true
      - name: "Prepare WebAssembly system"
        timeout-minutes: 10
        uses: r-universe-org/actions/linux-prep@v10
      - name: "Get dependences"
        id: deps
        uses: r-universe-org/actions/linux-deps@v10
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
          CRAN_VERSION: ${{ needs.prepare.outputs.cran_version }}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - id: build
        name: Build package "${{needs.source.outputs.package}}"
        uses: r-universe-org/actions/wasm-build@v10
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
          CRAN_VERSION: ${{ needs.prepare.outputs.cran_version }}
          NEED_CARGO: ${{ needs.source.outputs.cargo }}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: "Store package files"
        id: artifact
        uses: r-universe-org/actions/store-package@v10
        if: ${{ always() && steps.build.outputs.binarypkg }}
        with:
          name: package-wasm-${{ matrix.r }}
          JOB_STATUS: ${{ job.status }}
          FILE: ${{ steps.build.outputs.binarypkg }}
          TARGET: "wasm"
      - name: "${{'Conclude'}}: wasm-${{ matrix.r }}: ${{ steps.deps.outputs.rversion }}: ${{ steps.build.outputs.binarypkg && 'OK' || 'FAIL' }}: ${{ steps.artifact.outputs.artifact-id }}"
        run: echo "Artifact URL ${{steps.artifact.outputs.artifact-url}}"
        if: always()

  windows:
    needs: [prepare, source]
    if: ${{ always() && needs.source.outputs.sourcepkg && !needs.prepare.outputs.skip_binaries }}
    runs-on: 'windows-2025'
    timeout-minutes: 100
    name: Build R-${{ matrix.r }} for Windows
    strategy:
      fail-fast: false
      matrix:
        r: [ 'devel', 'release', 'oldrel' ]
    steps:
      - name: "Prepare Windows system"
        timeout-minutes: 10
        uses: r-universe-org/actions/windows-prep@v10
        with:
          java: ${{ needs.source.outputs.java }}
          jags: ${{ needs.source.outputs.jags }}
          quarto: ${{ needs.source.outputs.quarto }}
      - name: Install R-${{matrix.r}} for Windows
        timeout-minutes: 10
        uses: r-universe-org/actions/setup-r@v10
        id: install-r
        with:
          r-version: ${{ matrix.r }}
      - name: "Get dependences"
        id: deps
        uses: r-universe-org/actions/windows-deps@v10
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
          CRAN_VERSION: ${{ needs.prepare.outputs.cran_version }}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: Build package "${{needs.source.outputs.package}}"
        uses: r-universe-org/actions/windows-build@v10
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
          CRAN_VERSION: ${{ needs.prepare.outputs.cran_version }}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
          ostype: ${{ needs.source.outputs.ostype }}
      - name: "R CMD check"
        uses: r-universe-org/actions/windows-check@v10
        id: check
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
          CRAN_VERSION: ${{ needs.prepare.outputs.cran_version }}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: "Store binaries"
        id: artifact
        uses: r-universe-org/actions/store-package@v10
        if: ${{ always() && steps.check.outputs.binarypkg }}
        with:
          name: package-windows-${{ matrix.r }}
          JOB_STATUS: ${{ job.status }}
          DISTRO: windows
          FILE: ${{ steps.check.outputs.binarypkg }}
          CHECKSTATUS: ${{ steps.check.outputs.checkstatus }}
          TARGET: windows
      - name: "${{'Conclude'}}: windows-${{ matrix.r }}: ${{ steps.deps.outputs.rversion }}: ${{ steps.check.outputs.checkstatus || 'FAIL' }}: ${{ steps.artifact.outputs.artifact-id }}"
        run: echo "Artifact URL ${{steps.artifact.outputs.artifact-url}}"
        if: always()

  macos:
    needs: [prepare, source]
    if: ${{ always() && needs.source.outputs.sourcepkg && !needs.prepare.outputs.skip_binaries }}
    runs-on: macos-${{ matrix.arch == 'x86_64' && '15-intel' || '15' }}
    timeout-minutes: 120
    name: Build R-${{ matrix.r }} for MacOS ${{ needs.source.outputs.compiled && matrix.arch || '' }}
    strategy:
      fail-fast: false
      matrix:
        r: [ 'devel', 'release' ]
        arch: ${{fromJson(needs.source.outputs.matrix_macos)}}
    steps:
      - name: "Prepare macOS system"
        timeout-minutes: 10
        uses: r-universe-org/actions/macos-prep@v10
        with:
          version: ${{ matrix.r }}
          fortran: ${{ needs.source.outputs.fortran }}
          golang: ${{ needs.source.outputs.golang }}
          jags: ${{ needs.source.outputs.jags }}
          quarto: ${{ needs.source.outputs.quarto }}
      - name: Install R-${{matrix.r}} for MacOS
        timeout-minutes: 10
        uses: r-universe-org/actions/setup-r@v10
        id: install-r
        with:
          r-version: ${{ matrix.r }}
      - name: "Get dependences"
        id: deps
        uses: r-universe-org/actions/macos-deps@v10
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
          CRAN_VERSION: ${{ needs.prepare.outputs.cran_version }}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: Build package "${{needs.source.outputs.package}}"
        uses: r-universe-org/actions/macos-build@v10
        timeout-minutes: 90
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
          CRAN_VERSION: ${{ needs.prepare.outputs.cran_version }}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: "R CMD check"
        uses: r-universe-org/actions/macos-check@v10
        id: check
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: "Store binaries"
        id: artifact
        uses: r-universe-org/actions/store-package@v10
        if: ${{ always() && steps.check.outputs.binarypkg }}
        with:
          name: package-macos-${{ matrix.r }}-${{ matrix.arch }}
          JOB_STATUS: ${{ job.status }}
          DISTRO: macos
          FILE: ${{ steps.check.outputs.binarypkg }}
          CHECKSTATUS: ${{ steps.check.outputs.checkstatus }}
          TARGET: macos
      - name: "${{'Conclude'}}: macos-${{ matrix.r }}-${{ matrix.arch }}: ${{ steps.deps.outputs.rversion }}: ${{ steps.check.outputs.checkstatus || 'FAIL' }}: ${{ steps.artifact.outputs.artifact-id }}"
        run: echo "Artifact URL ${{steps.artifact.outputs.artifact-url}}"
        if: always()

  bioccheck:
    needs: [prepare, source]
    if: ${{ always() && needs.source.outputs.sourcepkg && needs.prepare.outputs.bioc_check }}
    runs-on: ubuntu-24.04
    timeout-minutes: 100
    name: Bioconductor Checks
    container:
      image: ghcr.io/r-universe-org/base-image:release
    outputs:
      checkresults: ${{ steps.check.outputs.checkresults }}
    steps:
      - name: "Prepare Linux system"
        timeout-minutes: 10
        uses: r-universe-org/actions/linux-prep@v10
      - name: "Get dependences"
        id: deps
        uses: r-universe-org/actions/linux-deps@v10
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
          CRAN_VERSION: ${{ needs.prepare.outputs.cran_version }}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: Run BiocCheck for "${{needs.source.outputs.package}}"
        uses: r-universe-org/actions/bioc-check@v10
        id: check
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
        with:
          sourcepkg: ${{ needs.source.outputs.sourcepkg }}
      - name: Store ${{needs.source.outputs.package}}.BiocCheck
        id: artifact
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: bioc-checks
          path: ${{needs.source.outputs.package}}.BiocCheck
      - name: "${{'Conclude'}}: bioc-checks: ${{ steps.deps.outputs.rversion }}: ${{ steps.check.outputs.checkstatus || 'FAIL' }}: ${{ steps.artifact.outputs.artifact-id }}"
        run: echo "Artifact URL ${{steps.artifact.outputs.artifact-url}}"
        if: always()

  deploy:
    name: Deploy to package server
    runs-on: ubuntu-24.04
    needs: [prepare, source, linux, windows, macos, wasm, docs, bioccheck]
    if: ${{ always() && needs.source.outputs.package }}
    outputs:
      deployed_packages: ${{ steps.deployment.outputs.deployed_packages }}
      version_change: ${{ steps.deployment.outputs.version_change }}
    steps:
      - id: download
        continue-on-error: true
        name: Download artifacts for deployment
        uses: actions/download-artifact@v7
      - if: steps.download.outcome == 'failure'
        name: Retry to download artifacts for deployment
        uses: actions/download-artifact@v7
      - id: deployment
        name: Upload packages to server
        uses: r-universe-org/actions/deploy-packages@v10
        env:
          CRANLIKEPWD: ${{ secrets.CRANLIKEPWD }}
          BIOC_CHECKS: ${{ needs.bioccheck.outputs.checkresults }}
          SKIP_BINARIES: ${{ needs.prepare.outputs.skip_binaries }}
          REPO_URL: ${{ needs.prepare.outputs.repo_url }}
          REPO_REGISTERED: ${{ needs.prepare.outputs.repo_registered }}
          COMMITINFO: ${{ needs.source.outputs.commitinfo }}
          MAINTAINERINFO: ${{ needs.source.outputs.maintainerinfo }}
          PACKAGE: ${{ needs.source.outputs.package }}
          VERSION: ${{ needs.source.outputs.version }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Report deployment failures in slack
        if: failure()
        uses: r-universe-org/actions/post-slack@v10
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          DEPLOY_STATUS: ${{ steps.deployment.outcome }}

  finalstatus:
    name: Set Github Status
    runs-on: ubuntu-24.04
    needs: [prepare, docs, source, deploy, pendingstatus]
    if: always() && needs.prepare.outputs.universe_app
    steps:
      - name: Set upstream commit status
        uses: r-universe-org/commit-status@master
        env:
          GH_APP_KEY: ${{ secrets.GH_APP_KEY }}
#          GITHUB_PAT: ${{ secrets.BOT_TOKEN }}
        with:
          repo: ${{ needs.prepare.outputs.repo_url }}
          sha: ${{ needs.prepare.outputs.repo_commit }}
          url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          universe: ${{ github.event.repository.name }}
          deployed_packages: ${{ needs.deploy.outputs.deployed_packages }}
          source_status: ${{ needs.source.result }}
          docs_status: ${{ needs.docs.result }}
          ostype: ${{ needs.source.outputs.ostype }}
          package: ${{ needs.prepare.outputs.repo_name }}
          has_app: ${{ needs.prepare.outputs.universe_app }}
          is_rebuild: ${{ needs.prepare.outputs.is_rebuild }}

  rechecks:
    name: Trigger rebuilds for dependents
    runs-on: ubuntu-24.04
    needs: [source, deploy]
    if: ${{ always() && needs.deploy.outputs.version_change }}
    steps:
      - name: Trigger rebuilds
        uses: r-universe-org/rebuilds@master
        env:
          GITHUB_PAT: ${{ secrets.BOT_TOKEN }}
          TRIGGER_REVDEPS: ${{ needs.source.outputs.package }}
